name: 'Tofu Post-Merge'

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
#  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  tofu-post-merge:
    name: 'Tofu Post-Merge'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: infra/lxd-cluster

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup tofu
        uses: hashicorp/setup-tofu@v1

      - name: tofu Init
        run: tofu init

      - name: tofu Plan (Post-Merge)
        run: tofu plan -input=false

      - name: tofu Apply (Post-Merge)
        run: tofu apply -auto-approve -input=false
        if: github.event.pull_request.merged == true