name: Tofu Pre-Merge

on:
  pull_request:

permissions:
  contents: read

env: 
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  tofu-check:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
        continue-on-error: true