name: Tofu Pre-Merge

on:
  pull_request:
    paths:
      - './infra/lxd-cluster/**.tf'
      - './infra/lxd-cluster/**.tfvars'
      - './infra/lxd-cluster/**.yaml'

permissions:
  contents: read

env: 
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  tofu-check:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: infra/lxd-cluster # convert to matrix later
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: opentofu/setup-opentofu@v1

      - name: Tofu Init
        run: tofu init

      - name: OpenTofu fmt
        id: fmt
        run: tofu fmt -check
      
      - name: Tofu Plan
        run: tofu plan -input=false
