#cloud-config
users:
  - name: rocky
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILzEMOzqt4lysezfFyw3qTTYnga/FhwHr4n93UnSz1Cv jimmy@gamebox
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: wheel
    shell: /bin/bash

runcmd:
  - systemctl enable sshd
  - systemctl start sshd
  - firewall-cmd --permanent --add-service=ssh
  - firewall-cmd --reload
